# To Do  - Clasificador de Supervivencia (Binario) del Titanic
[Data Source Link](https://www.kaggle.com/competitions/titanic/data?select=gender_submission.csv)
## EDA
### Tasks
  - Limpieza = Outliers, Datos Incorrectos o Faltantes
  - Visualizaciones (Insights)
  - Visualizaciones (Statistics)
    i.e Normalización
### Output
    - Armando - Cleaning.py 
    - 10 Visualizaciones Insights
        5 Chava
        5 Carlos
    - 10 Visualizaciones Statistics
        5 Grecia
        5 Omar
    - Variables Def, Interesantes, No Usables

## Feature Selection -> Predictores
  - Prueba Hipotesis 
  - Boruta (Decision Trees)

## Feature Engineering
  - Current Features Wrangling to New Features
  - Dataset Complementario

## Models Tranining -> Lista de Modelos
  - Model Base (male -> dies female-> survives)
  - Linear Regression
  - Xgboost
  - Adaboost
  - Lgbm
  - Neurona

## Best Model Optimization
  - Hyperparameters
  - Grid Search
  - Open CV

## Preguntas Insights
1. ¿Influye en la sobrevivencia del pasajero la clase en la que viaja?
2. ¿Qué rango de edad aumenta la probabilidad de sobrevivir?
3. ¿Influye el 'title' del pasajero en su sobrevivencia?
4. ¿Influye el sexo del pasajero en su sobrevivencia?
5. ¿Existen cabinas con mayor cercania a chalecos salvavidas o lanchas?
6. ¿Los sobrevivientes viajaban con familia?
7. ¿Los sobrevivientes pagaron una mayor tarifa?
8. ¿El puerto de embarcación  influye en la supervivencia del pasajero?
9. ¿El número de ticket tiene relación con la supervivencia?
10. ¿Tener un hijo influye en las posibilidades del pasajero de sobrevivir?


# Preguntas Statistics
1. Las varibles sibsp y parch son un factor irrelevante al momento de la supervivencia  
2. El número de camarote pudo ser relevante para sobrevivir según su ubicación en el barco y cercanía a salidas y/o salvavidas
3. El puerto de embarcación tiene relevancia para poder sobrevivir
4. Distribución de supervivencia según clase social
5. Distribución de supervivencia según sexo 
6. Distribución de clases según el puerto
7. Supervivencia según edad
8. Supervivencia según edad + sexo
9. Distribución de edad y clases
10. * Va a salir en cuanto se analicen los datos

# LIBRARIES

In [ ]:
import pandas as pd
from scipy.stats import describe
from typing import Tuple
import random 

# UTILS

In [ ]:
def explore(df: pd.DataFrame) -> pd.DataFrame:
    ex1, ex2, ex3 = random.sample(range(len(df)), 3)

    print("Dataframe total rows: ", len(df))
    df_info = pd.DataFrame(data = df.dtypes)
    not_missing_values_total = df.notnull().sum()
    not_missing_values_percent = round(not_missing_values_total/len(df)*100,2).astype(str)+" %"

    return pd.concat([df_info[0].rename("Data Type"),\
            df.T[ex1].rename("Example 1"),\
            df.T[ex2].rename("Example 2"),\
            df.T[ex3].rename("Example 3"),\
            not_missing_values_total.rename("Total Not Missing"), \
            not_missing_values_percent.rename("% of not missing values")], axis=1)

# DATA

In [ ]:
import pandas as pd
df_og = pd.read_csv("/work/data/train.csv")
df_og

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

# DATA CLEANING

In [ ]:
# Variables to consider
df_clean = df_og.drop(['Name', 'PassengerId', 'Ticket', 'SibSp', 'Parch', 'Fare'], axis=1)

## INSPECTION

In [ ]:
display(df_clean.head())
display(df_clean.tail())

Survived  Pclass     Sex   Age Cabin Embarked
0         0       3    male  22.0   NaN        S
1         1       1  female  38.0   C85        C
2         1       3  female  26.0   NaN        S
3         1       1  female  35.0  C123        S
4         0       3    male  35.0   NaN        S

Survived  Pclass     Sex   Age Cabin Embarked
886         0       2    male  27.0   NaN        S
887         1       1  female  19.0   B42        S
888         0       3  female   NaN   NaN        S
889         1       1    male  26.0  C148        C
890         0       3    male  32.0   NaN        Q

In [ ]:
display(df_clean.info())
display(explore(df_clean))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    object 
 3   Age       714 non-null    float64
 4   Cabin     204 non-null    object 
 5   Embarked  889 non-null    object 
dtypes: float64(1), int64(2), object(3)
memory usage: 41.9+ KB


None

Dataframe total rows:  891


Data Type Example 1 Example 2 Example 3  Total Not Missing  \
Survived     int64         1         0         0                891   
Pclass       int64         2         3         3                891   
Sex         object    female      male      male                891   
Age        float64      42.0      14.0       NaN                714   
Cabin       object       NaN       NaN       NaN                204   
Embarked    object         S         S         Q                889   

         % of not missing values  
Survived                 100.0 %  
Pclass                   100.0 %  
Sex                      100.0 %  
Age                      80.13 %  
Cabin                     22.9 %  
Embarked                 99.78 %

### NUMERIC


In [ ]:
display(describe(df_clean.select_dtypes(include ='number'), axis=0))
print("\n")
display(df_clean.describe())
print("\n")

DescribeResult(nobs=891, minmax=(array([ 0.,  1., nan]), array([ 1.,  3., nan])), mean=array([0.38383838, 2.30864198,        nan]), variance=array([0.23677222, 0.69901512,        nan]), skewness=array([ 0.47771747, -0.62948588,         nan]), kurtosis=array([-1.77178602, -1.27956968,         nan]))

Survived      Pclass         Age
count  891.000000  891.000000  714.000000
mean     0.383838    2.308642   29.699118
std      0.486592    0.836071   14.526497
min      0.000000    1.000000    0.420000
25%      0.000000    2.000000   20.125000
50%      0.000000    3.000000   28.000000
75%      1.000000    3.000000   38.000000
max      1.000000    3.000000   80.000000

### NON NUMERIC


In [ ]:
display(df_clean.select_dtypes(include ='object').describe(include = 'O').T)

count unique          top freq
Sex        891      2         male  577
Cabin      204    147  C23 C25 C27    4
Embarked   889      3            S  644

# FIXING


In [ ]:
def imputing(df:pd.DataFrame) -> pd.DataFrame:
    var_types = {
        "number"    :   "median",
        "object"    :   "mode"
    }
    for var_type in list(var_types.keys()):
        for col in df.select_dtypes(include=var_type).columns: 
            df[col] = df[col].fillna(getattr(df[col], var_types[var_type])())
    return df

def encoding(df:pd.DataFrame) -> pd.DataFrame:
    sex = {
        "male"  :   0,
        "female":   1
    }
    embarked = {
        "C" :   0,
        "Q" :   1,
        "S" :   2
    }    
    df['Sex'] = df['Sex'].map(sex)
    df['Embarked'] = df['Embarked'].map(embarked)
    return df

# NAN, NULLS - Age, Cabin, Embarked
df_clean = imputing(df_clean)
# ENCODING - Sex, Embarked
df_clean = encoding(df_clean)


In [ ]:
df_clean.head()

Survived  Pclass  Sex   Age    Cabin  Embarked
0         0       3    0  22.0  B96 B98       2.0
1         1       1    1  38.0      C85       0.0
2         1       3    1  26.0       G6       2.0
3         1       1    1  35.0     C123       2.0
4         0       3    0  35.0      NaN       2.0

# BASELINE MODEL

In [ ]:
# IF female -> survived ELSE died
df_clean["Output"] =  df_clean['Sex']
df_clean

Survived  Pclass  Sex   Age    Cabin  Embarked  Output
0           0       3    0  22.0  B96 B98       2.0       0
1           1       1    1  38.0      C85       0.0       1
2           1       3    1  26.0       G6       2.0       1
3           1       1    1  35.0     C123       2.0       1
4           0       3    0  35.0      NaN       2.0       0
..        ...     ...  ...   ...      ...       ...     ...
886         0       2    0  27.0      NaN       2.0       0
887         1       1    1  19.0      B42       2.0       1
888         0       3    1  28.0      NaN       2.0       1
889         1       1    0  26.0     C148       0.0       0
890         0       3    0  32.0      NaN       1.0       0

[891 rows x 7 columns]

In [ ]:
from sklearn import metrics
confusion_matrix = metrics.confusion_matrix(df_clean["Survived"], df_clean["Output"])

print(confusion_matrix)
print(metrics.classification_report(df_clean["Survived"], df_clean["Output"]))

[[468  81]
 [109 233]]
              precision    recall  f1-score   support

           0       0.81      0.85      0.83       549
           1       0.74      0.68      0.71       342

    accuracy                           0.79       891
   macro avg       0.78      0.77      0.77       891
weighted avg       0.78      0.79      0.78       891



# Initial Models
Just to play with the data

In [ ]:
!pip install boruta==0.3

You should consider upgrading via the '/root/venv/bin/python -m pip install --upgrade pip' command.


In [ ]:
import numpy as np
from sklearn.ensemble import RandomForestRegressor
 
# feature engineering
from boruta import BorutaPy
estimator = RandomForestRegressor()

x = df_clean.select_dtypes(include ='number').drop(['Survived','Output'], axis = 1).fillna(0) 
y = df_clean["Survived"]
boruta = BorutaPy(estimator = estimator, n_estimators = 'auto', max_iter = 100)
boruta.fit(np.array(x), np.array(y))

# Important features
important = list(x.columns[boruta.support_])
print(f"Features confirmed as important:   {important}")

# Other features
print(f"\nUnconfirmed features (tentative):  {list(x.columns[boruta.support_weak_])}")
print(f"\nFeatures confirmed as unimportant: {list(x.columns[~(boruta.support_ | boruta.support_weak_)])}")

Features confirmed as important:   ['Sex', 'Age']

Unconfirmed features (tentative):  []

Features confirmed as unimportant: ['Pclass', 'Embarked']


In [ ]:
from sklearn.neighbors import KNeighborsClassifier

small_x = df_clean[["Age", "Sex"]]
model = KNeighborsClassifier(n_neighbors=2)
model.fit(small_x, y)
y_pred = model.predict(small_x)

# Confusion Matrix
confusion_matrix = metrics.confusion_matrix(y, y_pred)
print(confusion_matrix)
print(metrics.classification_report(y, y_pred))

[[513  36]
 [160 182]]
              precision    recall  f1-score   support

           0       0.76      0.93      0.84       549
           1       0.83      0.53      0.65       342

    accuracy                           0.78       891
   macro avg       0.80      0.73      0.74       891
weighted avg       0.79      0.78      0.77       891



In [ ]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier(max_depth =3, random_state = 42)
model.fit(small_x, y)
y_pred = model.predict(small_x)
confusion_matrix = metrics.confusion_matrix(y,y_pred)
print(confusion_matrix)
print(metrics.classification_report(y, y_pred))

[[460  89]
 [ 92 250]]
              precision    recall  f1-score   support

           0       0.83      0.84      0.84       549
           1       0.74      0.73      0.73       342

    accuracy                           0.80       891
   macro avg       0.79      0.78      0.78       891
weighted avg       0.80      0.80      0.80       891



In [ ]:
from sklearn.model_selection import GridSearchCV

model = DecisionTreeClassifier(max_depth =3, random_state = 0)
params = {'max_depth': range(1,10), 
          'min_samples_leaf' : range(1,10),
          'min_samples_split': [2, 3] + np.arange(0.1, 0.9, 0.1).tolist(),
          'criterion' : ['gini', 'entropy']
        }
scores = ['recall', 'precision', 'f1']
for score in scores:
    print(f"Tuning for {score}")    
    clf = GridSearchCV(
        model, params,
        cv = 10,
        n_jobs = -1, 
        scoring = f'{score}_macro',
        verbose = 0,
        refit = True)
    clf.fit(small_x, y)
    print(clf.best_params_)
    print(clf.best_score_, '\n\n')
    model =  clf.best_estimator_

print("FINAL")
print(clf.best_params_)
print(clf.best_score_)

Tuning for recall
{'criterion': 'gini', 'max_depth': 3, 'min_samples_leaf': 7, 'min_samples_split': 2}
0.7781876184817362 


Tuning for precision
{'criterion': 'gini', 'max_depth': 3, 'min_samples_leaf': 7, 'min_samples_split': 2}
0.7838203156348194 


Tuning for f1
{'criterion': 'gini', 'max_depth': 3, 'min_samples_leaf': 7, 'min_samples_split': 2}
0.7788315946715172 


FINAL
{'criterion': 'gini', 'max_depth': 3, 'min_samples_leaf': 7, 'min_samples_split': 2}
0.7788315946715172


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=34b6ad67-9899-4609-8c36-e96f39426d07' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>